// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZIBNEJdUetNO0NIJk0hlv-2wyJjSsTEw',
    appId: '1:926025922131:web:233c2eff8f2c2f80f338a6',
    messagingSenderId: '926025922131',
    projectId: 'dayss-921fc',
    authDomain: 'dayss-921fc.firebaseapp.com',
    storageBucket: 'dayss-921fc.appspot.com',
    measurementId: 'G-JEV2Q71TYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs2lpI5bmUuC8pC2vkXla6bqopD4ri0Vk',
    appId: '1:926025922131:android:9e3ed4570cfb14fff338a6',
    messagingSenderId: '926025922131',
    projectId: 'dayss-921fc',
    storageBucket: 'dayss-921fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB35xwMhcTio9Eo9g9v2rQyRW4iutkWP4',
    appId: '1:926025922131:ios:d52415952242e678f338a6',
    messagingSenderId: '926025922131',
    projectId: 'dayss-921fc',
    storageBucket: 'dayss-921fc.appspot.com',
    iosBundleId: 'com.example.thirtyWidgets',
  );
}
